### PR TITLE
SRCH-4042 use Ruby 3.0.6

### PR DESCRIPTION
**Pull request by MothOnMars**
## Summary
This PR updates ASIS to use Ruby 3.0.6.
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks
 
- [x] You have merged the latest changes from the target branch (usually `main`) into your branch.
 
- [x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [x] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [x] You have specified at least one "Reviewer".

### CODE REVIEW

**Review by MyNameIsMissing — DISMISSED** [review]
LGTM

**Comment by MothOnMars** [comment]
@MyNameIsMissing , re-review needed for a minor bit of housekeeping.

**Review by MyNameIsMissing — APPROVED** [review]
LGTM

**Comment by MothOnMars** [comment]
I just noticed that 3.0.6 was released on 3/30. So, once more with feeling...

**Review by MyNameIsMissing — DISMISSED** [review]
LGTM

**Comment by MothOnMars** [comment]
Adding the "do not merge" label. This won't be deployable until Ruby 3.0.6 is installed in production: https://cm-jira.usa.gov/browse/SRCH-3862

**Comment by MothOnMars** [comment]
@MyNameIsMissing , this needs a re-review. Our PRs currently require status checks from 2.7.5 and 3.0.5, so I've added those back to the test matrix. The old versions will be removed, and the PR status checks will be updated in a follow-up ticket: https://cm-jira.usa.gov/browse/SRCH-3880

**Review by MyNameIsMissing — APPROVED** [review]
LGTM

**Pull request merged**
