### PR TITLE
SRCH-4032 use Ruby 2.7.5

### PR DESCRIPTION
**Pull request by MothOnMars**
## Summary
This PR temporarily sets our version of Ruby back to 2.7.5. With the installation of Fullstaq, we will use `.ruby-version` in production, so this keeps us on our current version until we're ready to upgrade to 3.0.5.
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks
 
- [x] You have merged the latest changes from the target branch (usually `main`) into your branch.
 
- [x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
⚠️  Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
- The only change in this PR is to the Ruby version. We'll address any Rubocop issues in the code once we've upgraded to Ruby 3.0.x, and no longer need to support 2.7.
 
#### Process Checks

- [x] You have specified at least one "Reviewer".

### CODE REVIEW

**Review by yogesh27 — COMMENTED** [review]
LGTM

**Comment by MothOnMars** [comment]
@yogesh27 , see my comments in the PR description.

**Comment by yogesh27** [comment]
> @yogesh27 , see my comments in the PR description.

Got it. PR looks good to me in that case.

**Comment by MothOnMars** [comment]
@yogesh27 , please approve the PR. :)

**Review by yogesh27 — APPROVED** [review]
LGTM

**Pull request merged**
